# azure-pipelines-ci.yml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x' # Specify the .NET SDK version you are using
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore src/DotNetCoreWebApp/DotNetCoreWebApp.csproj
  displayName: 'Restore NuGet Packages'

- script: dotnet build src/DotNetCoreWebApp/DotNetCoreWebApp.csproj --configuration Release --no-restore
  displayName: 'Build the Application'

- script: dotnet test tests/DotNetCoreWebApp.Tests/DotNetCoreWebApp.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"
  displayName: 'Run Tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'src/DotNetCoreWebApp/bin/Release/net6.0/publish' # Adjust the path based on your project structure
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DotNetCoreWebApp.zip'
    replaceExistingArchive: true

- publish: '$(Build.ArtifactStagingDirectory)/DotNetCoreWebApp.zip'
  artifact: 'drop'
